// <auto-generated />
using System;
using CalibrationMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalibrationMvc.Migrations
{
    [DbContext(typeof(CalibrationDbContext))]
    [Migration("20260409161951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalibrationMvc.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalibrationId")
                        .HasColumnType("int");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Calibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CalibratedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("Pressure")
                        .HasColumnType("decimal(7,1)");

                    b.Property<int>("ReferenceDeviceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ReferenceDeviceId");

                    b.ToTable("Calibrations");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.CalibrationFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalibrationId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.ToTable("CalibrationFiles");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.CalibrationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CalibrationTypes");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CalibratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CalibrationFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationOfUse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MaxRange")
                        .HasColumnType("decimal(18,7)");

                    b.Property<string>("MeasurementAccuracy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MinRange")
                        .HasColumnType("decimal(18,7)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NextCalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcedureNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TechnicalTolerance")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("MachineId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.DeviceVerificationValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("PointNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToleranceValue")
                        .HasColumnType("decimal(18,7)");

                    b.Property<decimal?>("UncertaintyValue")
                        .HasColumnType("decimal(18,7)");

                    b.Property<decimal>("VerificationValue")
                        .HasColumnType("decimal(18,7)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceVerificationValues");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.MeasurementPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbsoluteDifference")
                        .HasColumnType("decimal(18,7)");

                    b.Property<decimal>("AscendingValue")
                        .HasColumnType("decimal(18,7)");

                    b.Property<int>("CalibrationId")
                        .HasColumnType("int");

                    b.Property<decimal>("DescendingValue")
                        .HasColumnType("decimal(18,7)");

                    b.Property<decimal>("Hysteresis")
                        .HasColumnType("decimal(18,7)");

                    b.Property<int>("PointNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Tolerance")
                        .HasColumnType("decimal(18,7)");

                    b.Property<decimal>("Uncertainty")
                        .HasColumnType("decimal(18,7)");

                    b.Property<decimal>("VerificationValue")
                        .HasColumnType("decimal(18,7)");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationId");

                    b.ToTable("MeasurementPoints");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalibrationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProcedureNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationTypeId");

                    b.HasIndex("ProcedureNumber")
                        .IsUnique();

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.Calibration", "Calibration")
                        .WithMany()
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalibrationMvc.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalibrationMvc.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalibrationMvc.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calibration");

                    b.Navigation("Device");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Calibration", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalibrationMvc.Entities.Device", "Device")
                        .WithMany("Calibrations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalibrationMvc.Entities.Device", "ReferenceDevice")
                        .WithMany()
                        .HasForeignKey("ReferenceDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Device");

                    b.Navigation("ReferenceDevice");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.CalibrationFile", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.Calibration", "Calibration")
                        .WithMany("Files")
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calibration");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Device", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.Machine", "Machine")
                        .WithMany("Devices")
                        .HasForeignKey("MachineId");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.DeviceVerificationValue", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.Device", "Device")
                        .WithMany("VerificationValues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Machine", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.Department", "Department")
                        .WithMany("Machines")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.MeasurementPoint", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.Calibration", "Calibration")
                        .WithMany("MeasurementPoints")
                        .HasForeignKey("CalibrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calibration");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Procedure", b =>
                {
                    b.HasOne("CalibrationMvc.Entities.CalibrationType", "CalibrationType")
                        .WithMany()
                        .HasForeignKey("CalibrationTypeId");

                    b.Navigation("CalibrationType");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Calibration", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("MeasurementPoints");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Department", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Device", b =>
                {
                    b.Navigation("Calibrations");

                    b.Navigation("VerificationValues");
                });

            modelBuilder.Entity("CalibrationMvc.Entities.Machine", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
